import type { HingeParams } from './types';

export interface HingePaths {
  cuts:    string;  // SVG path string — lines to cut
  outline: string;  // SVG path string — material boundary (rect)
  rowCount: number;
  density: number;  // 0–1 approx material removed ratio
}

/** Straight alternating-edge cuts — most effective for single-axis flex */
function kerfPaths(p: HingeParams): HingePaths {
  const { width: W, height: H, rowSpacing: rs, bridge: br } = p;
  const segs: string[] = [];
  let y = rs / 2;
  let row = 0;
  while (y <= H) {
    if (row % 2 === 0) {
      segs.push(`M 0,${y.toFixed(3)} L ${(W - br).toFixed(3)},${y.toFixed(3)}`);
    } else {
      segs.push(`M ${br.toFixed(3)},${y.toFixed(3)} L ${W.toFixed(3)},${y.toFixed(3)}`);
    }
    y += rs;
    row++;
  }
  const rowCount = row;
  return {
    cuts: segs.join(' '),
    outline: `M 0,0 L ${W},0 L ${W},${H} L 0,${H} Z`,
    rowCount,
    density: rowCount * (W - br) / (W * H),
  };
}

/** Sinusoidal cuts — smoother flex, more aesthetic */
function wavePaths(p: HingeParams): HingePaths {
  const { width: W, height: H, rowSpacing: rs, bridge: br, amplitude: amp } = p;
  const segs: string[] = [];
  const STEPS = 48;
  let y = rs / 2;
  let row = 0;

  function waveSeg(x0: number, x1: number, cy: number, phase: number): string {
    const pts: string[] = [];
    for (let i = 0; i <= STEPS; i++) {
      const t  = i / STEPS;
      const x  = x0 + t * (x1 - x0);
      const wy = cy + amp * Math.sin((t * Math.PI * 2) + phase);
      pts.push(`${i === 0 ? 'M' : 'L'} ${x.toFixed(2)},${wy.toFixed(2)}`);
    }
    return pts.join(' ');
  }

  while (y <= H) {
    if (row % 2 === 0) {
      segs.push(waveSeg(0, W - br, y, 0));
    } else {
      segs.push(waveSeg(br, W, y, Math.PI));
    }
    y += rs;
    row++;
  }

  return {
    cuts: segs.join(' '),
    outline: `M 0,0 L ${W},0 L ${W},${H} L 0,${H} Z`,
    rowCount: row,
    density: row * (W - br) / (W * H),
  };
}

/** Short offset cuts — allows multi-axis flex, lattice-like appearance */
function crossPaths(p: HingeParams): HingePaths {
  const { width: W, height: H, rowSpacing: rs, cutLength: cl, cutGap: cg } = p;
  const segs: string[] = [];
  let y = rs / 2;
  let row = 0;

  while (y <= H) {
    const offset = (row % 2) * ((cl + cg) / 2);
    let x = offset;
    while (x < W) {
      const x1 = Math.min(x + cl, W);
      if (x1 - x > 0.5) {
        segs.push(`M ${x.toFixed(3)},${y.toFixed(3)} L ${x1.toFixed(3)},${y.toFixed(3)}`);
      }
      x += cl + cg;
    }
    y += rs;
    row++;
  }

  return {
    cuts: segs.join(' '),
    outline: `M 0,0 L ${W},0 L ${W},${H} L 0,${H} Z`,
    rowCount: row,
    density: 0.5,
  };
}

export function generateHingePaths(p: HingeParams): HingePaths {
  switch (p.pattern) {
    case 'wave':  return wavePaths(p);
    case 'cross': return crossPaths(p);
    default:      return kerfPaths(p);
  }
}

export function downloadHingeSVG(p: HingeParams, paths: HingePaths): void {
  const pad = 4;
  const W = p.width + pad * 2;
  const H = p.height + pad * 2;
  const svg = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${W}mm" height="${H}mm"`,
    `     viewBox="${-pad} ${-pad} ${W} ${H}">`,
    `  <!-- Material boundary -->`,
    `  <path d="${paths.outline}" fill="none" stroke="#000" stroke-width="0.1"/>`,
    `  <!-- Living hinge cuts -->`,
    `  <path d="${paths.cuts}" fill="none" stroke="#000" stroke-width="0.05"/>`,
    `</svg>`,
  ].join('\n');

  const blob = new Blob([svg], { type: 'image/svg+xml' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `hinge_${p.pattern}_${p.width}x${p.height}.svg`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadHingeDXF(p: HingeParams, paths: HingePaths): void {
  // DXF R12, 1 unit = 1 mm — polyline per cut segment
  const { width: W, height: H, rowSpacing: rs, bridge: br } = p;

  function dxfLine(x1: number, y1: number, x2: number, y2: number, layer = 'HINGE'): string {
    return [
      '0\nLINE',
      `8\n${layer}`,
      `10\n${x1.toFixed(4)}`, `20\n${(-y1).toFixed(4)}`, `30\n0`,
      `11\n${x2.toFixed(4)}`, `21\n${(-y2).toFixed(4)}`, `31\n0`,
    ].join('\n');
  }

  const lines: string[] = [];
  // Outline
  lines.push(dxfLine(0, 0, W, 0, 'OUTLINE'));
  lines.push(dxfLine(W, 0, W, H, 'OUTLINE'));
  lines.push(dxfLine(W, H, 0, H, 'OUTLINE'));
  lines.push(dxfLine(0, H, 0, 0, 'OUTLINE'));

  // Cut lines (kerf only in DXF for simplicity)
  let y = rs / 2;
  let row = 0;
  while (y <= H) {
    if (row % 2 === 0) {
      lines.push(dxfLine(0, y, W - br, y));
    } else {
      lines.push(dxfLine(br, y, W, y));
    }
    y += rs;
    row++;
  }

  const header = `999\nDXF generated by Studio FAB\n0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n4\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n`;
  const footer = `0\nENDSEC\n0\nEOF`;
  const content = header + lines.join('\n') + '\n' + footer;

  const blob = new Blob([content], { type: 'application/dxf' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `hinge_${p.pattern}_${p.width}x${p.height}.dxf`;
  a.click();
  URL.revokeObjectURL(url);
}
